name: release

on:
  push:
    branches: 
      - main

jobs:

  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Publish on gh-pages branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npm ci
        npm run publish -- -u "${{ secrets.GIT_USER }} <${{ secrets.GIT_EMAIL }}>"
    