name: release

on:
  push:
    branches: 
      - main

jobs:

  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Publish on gh-pages branch
      run: |
        npm ci
        npm run publish
    